apiVersion: v1
kind: Service
metadata:
  name: wms-system-custom
  labels:
    app: wms-system-custom
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: wms-system-custom
